### ISSUE TITLE
Allows sitters change(update) information on the profile page

### ISSUE THREAD

**Issue by NadzeyaShpakouskaya** [IronFoundation/iOS-Woof#38]
## The scope of the current task:
- #8 
- #44

## Description
In the current version, the sitter can only enter information about themselves only once. 
Users should be able to change any info about themselves on their profile page. 
The button `Edit` should be visible at all times. 

### Dev requirements and restrictions:
- [x] need backend endpoint to update the info
- [x] refactor the `SitterProfileView`
- [x] refactor the `SitterProfileViewModel` when we need to satisfy the restriction when should make a post or a put request.

**Comment by NadzeyaShpakouskaya** [comment]
All subtasks have been finished.
